// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class change_Guid_InsetadOf_Id_Questions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_Guid_InsetadOf_Id_Questions));
        
        string IMigrationMetadata.Id
        {
            get { return "202005141526537_change_Guid_InsetadOf_Id_Questions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
